global:
  logging:
    format: text
    level: info
  
  # Toleration щоб Pods могли розміщуватися на GPU вузлах, якщо CPU-вузли перевантажені
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

server:
  service:
    type: ClusterIP
  
  # Зменшення реплік ArgoCD Server для уникнення недостатку ресурсів на подах
  replicaCount: 1 
  
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

controller:
  extraArgs:
    - --status-processors=20
    - --operation-processors=10
    
  # Зменшення реплік Application Controller
  replicaCount: 1 
    
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

repoServer:
  extraArgs: []
  
  # Зменшення реплік Repo Server 
  replicaCount: 1
    
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

applicationSet:
  enabled: true
  # applicationSet-controller зазвичай має 1 репліку за замовчуванням, але для повноти можна вказати явно
  # replicaCount: 1 
  
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

configs:
  params:
    server.insecure: "true"
    server.readiness.timeout: "10s"
    server.request.timeout: "180s"

  rbac:
    policy.default: role:readonly

  cm:
    users.anonymous.enabled: "true"

dex:
  enabled: false

notifications:
  enabled: false
